### ISSUE TITLE
[Bug] TCGC incorrectly creates a model for some types

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#107]
For https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/payload/content-negotiation/main.tsp#L55-L58

I don't think this is a "real" model, but TCGC creates one for it.

Interestingly, I don't see one being generated for `PngImage` from the same tsp.

**Comment by iscai-msft** [comment]
This one we should talk about more. The reason `PngImage` isn't created as a model is because all of the properties are explicitly parameters. In the case of `PngImageAsJson`, the `content` property could be a property of a body model. We should be digging more into the context that this model is used though. If it's only spread on a function's signature, then we shouldn't generate it
