### ISSUE TITLE
[Feature Request][TCGC] flatten property in model hierarchy

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#111]
**Is your feature request related to a problem? Please describe.**
After we added `@flattenProperty` decorator in #13, the next question is whether we should calculate flattened property in TCGC model hierarchy?

Here is the questionnaire for each language emitter:

| language | do we need to flatten property in TCGC |
|----|----|
| Python | better to have |
| Java | no |
| Csharp | Yes |
| JavaScript| ? |
| Go | N/A no flatten support |

**Describe the solution you'd like**
To minimize the integration efforts, I expect in the TCGC model hierarchy, we do the similar thing like `flattenedNames` in moduler-four:
- flatten property to the target model, i.e. TCGC model should reflect the final model, not the original definition in TSP
- for each flattened property, provide a property like `flattenedNames` to indicate the location in the serialization/deserialization JSON hierarchy

**Describe alternatives you've considered**
Each language can implement their own logic to calculating metadata of flatten properties, like Java does.

**Comment by weidongxu-microsoft** [comment]
Java would require TCGC have the option NOT to flatten like m4. It only needs `shouldFlattenProperty(..)`.

**Comment by archerzz** [comment]
> Java would require TCGC have the option NOT to flatten like m4. It only needs `shouldFlattenProperty(..)` that already in TCGC.

How does Java handle modeler-four output? There is a flag to tell modeler-four not to flatten?

**Comment by weidongxu-microsoft** [comment]
> How does Java handle modeler-four output? There is a flag to tell modeler-four not to flatten?

It is off.
https://github.com/Azure/autorest.java/blob/main/fluentgen/readme.md?plain=1#L52

(and we are asking same for TCGC)

**Comment by qiaozha** [comment]
JS also doesn't need the flattened model, because RLC doesn't need to support flatten.

**Comment by iscai-msft** [comment]
Since `@flattened` is something that we want to deprecate, and because language behavior around `@flattened` isn't consistent (for example, Python still generates it like before, we just add some magic to get flattening to work), I've talked to @lmazuel and we don't think we should do anything fancy with `@flattened`. Instead, you can look at the [`.flatten`](https://github.com/Azure/typespec-azure/blob/main/packages/typespec-client-generator-core/src/interfaces.ts#L330) property on a body model property type.

I'm going to close this issue because of @lmazuel's input, if this is still a strong ask, please reopen. Thanks!
