### ISSUE TITLE
[tcgc] lro info in tcgc interface

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#1236]
currently, if an operation is lro, then the service method's response in tcgc will be the logic result of the operation, and `resultPath` will show the `finalResultPath` of the lro metadata. from emitter's feedback, the envelop result is also usable in sdk code. so, we need to add more info to current tcgc interface.

@haolingdong-msft @archerzz @qiaozha could you help to list all the info you used from `getLroMetadata`? thanks

**Comment by haolingdong-msft** [comment]
For Java, we need polling information, especially polling response type.

BTW, does this issue includes this one I created before? https://github.com/Azure/typespec-azure/issues/1062 If so, I can close mine.

**Comment by qiaozha** [comment]
JS is using the following info, @MaryGao  could help correct me if I miss anything. 
1. finalResult
2. finalStateVia
3. finalResultPath
4. finalStep

**Comment by MaryGao** [comment]
> JS is using the following info, @MaryGao could help correct me if I miss anything.
> 
> 1. finalResult
> 2. finalStateVia
> 3. finalResultPath
> 4. finalStep

Yes, JS used 4 above but if we focus on the modular(because RLC would not refer TCGC) I think the top 3 are enough.
1. finalResult used to calculate operation return type
2. finalStateVia just placeholder for now and mainly for final-state-via information
3. finalResultPath used to calcuate deserliazation path
