### ISSUE TITLE
[TCGC] `api-version` parameter should not be `onClient===true` if the server is non-versioned

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#1391]
Case: 
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/server/versions/not-versioned/main.tsp#L33

This is a non-versioned client, and I think the `api-version` should not be on client, but TCGC mark it as` onClient`.
TCGC output:
![image](https://github.com/user-attachments/assets/f6cdb889-a25b-4b1c-9274-b41505b67387)

Seems  a bug in TCGC?

**Comment by iscai-msft** [comment]
Our current behavior is that we will always elevate `api-version` onto the client. It does make sense that versioning corresponds to setting api versioning on clients, but I do think we should talk about this in scrum on weds. Adding that to the agenda list

**Comment by haolingdong-msft** [comment]
Sure, let's have discussion how the generated sdk should look like for non-versioned clients, I think we should not add api-version to the client parameter, otnerwise  it is not **non-versioned** client.
For Java, if it is a non-versioned client, we will not add api-version parameter to the client. How about other languages? 
/cc @iscai-msft @tadelesh @archerzz @chunyu3 @qiaozha @MaryGao

**Comment by archerzz** [comment]
C# doesn't check `onClient`. C# emitter will pass the `api-version` method parameter to the generator. And generator will check if there is already a client parameter `api-version`. If so, the method parameter will be suppressed: https://github.com/Azure/autorest.csharp/blob/bb1c49bfd05512775ed080679152e5cad1f64211/src/AutoRest.CSharp/Common/Generation/Writers/RequestWriterHelpers.cs#L291-L301

What's `onClient` for? Does it indicate that the query parameter already exists on client level?

**Comment by haolingdong-msft** [comment]
Hi @archerzz , from my understanding, `onClient` is used to decide whether the parameter should be on client or not. And emitter is expected to use this value to decide whether to put the parameter on client. This is also related with Izzy's latest [pr ](https://github.com/Azure/typespec-azure/pull/1398) as well,  which adds client parameters to the client initialization object. Those parameters will also have `onClient==true` on `SdkHttpOperation`.

**Comment by haolingdong-msft** [comment]
Summary on 9/5 meeting:
1. TCGC will mark `onClient` as `false` for api-version in non-versioned clients.
2. (TBD) what should we set for `isApiVersion` flag on the parameter.

**Comment by archerzz** [comment]
Another proposal: just delete `onClient`, because where you get `SdkParameter` should already tell you.

- check `SdkClientType.initialization`: https://github.com/Azure/typespec-azure/blob/85d0f982f16cfb6ac44a85c989db17a7ae948064/packages/typespec-client-generator-core/src/interfaces.ts#L101 which contains an array of `SdkParameter`: https://github.com/Azure/typespec-azure/blob/85d0f982f16cfb6ac44a85c989db17a7ae948064/packages/typespec-client-generator-core/src/interfaces.ts#L381-L383
- any `SdkParameter` from `SdkClientType.initialization.properties` should be `onClient: true`
- any `SdkParawmeter` from `SdkServiceMethodBase.parameters` should be `onClient: false`: https://github.com/Azure/typespec-azure/blob/85d0f982f16cfb6ac44a85c989db17a7ae948064/packages/typespec-client-generator-core/src/interfaces.ts#L601
- so, we could remove `onClient` property, because:
  - If you think an `SdkParameter` should be `onClient: true`, just put it in `SdkClientType.initialization.properties`
  - If you think an `SdkParameter` should be `onClient: false`, just put it in any place other than `SdkClientType.initialization.properties` (e.g. `SdkServiceMethodBase.parameters`)

**Comment by haolingdong-msft** [comment]
> Another proposal: just delete `onClient`, because where you get `SdkParameter` should already tell you.

Hi @mingzhe, Personally I think these logics you mentioned on calculating `onClient` value should be better to put to TCGC, and emitters only need to rely on `onClient` value. Add @tadelesh and @iscai-msft  for more comments as well.

**Comment by iscai-msft** [comment]
@mingzhe that is a good point, where we might no longer need `onClient`. I'm going to open another issue about this, and see what can be done. Thanks!

**Comment by chunyu3** [comment]
I think we should keep `onClient` flag. When we do `@clientInitialization` to bump a parameter from operation to client. .NET need to know if the client parameter is exactly the client parameter or it is a parameter which is bumped from operation. Current we use  `onClient` flag in the parameter of an operation to identify that this operation parameter is bumped to client.

**Comment by haolingdong-msft** [comment]
Hi @iscai-msft, I would agree with @chunyu3 , I think checking `onClient` is the most straightforward and easiest way, though one can also argue  that emitter could check whether the parameter is in `SdkClientType.initialization.properties` or not to determine if it's `onClient`. Both ways are workable, personally I would prefer the easier way which is to use `onClient`, and I think most language emitters are doing so already or planning to do so. Removing `onClient` would cause breaking changes to those emitters.
