### ISSUE TITLE
[tcgc] Support @typespec/openapi3 in scope

### ISSUE THREAD

**Issue by wanlwanl** [Azure/typespec-azure#1738]
### Clear and concise description of the problem

openapi3 and TCGC are used together for service team now. e.g. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/ai/OpenAI.Assistants/tspconfig.yaml#L10

But the current implemetation doesn't support @typespec/openapi3 due to: https://github.com/Azure/typespec-azure/blob/0ec010641fb6bd9ab41ca722bea89d67da552ffe/packages/typespec-client-generator-core/src/internal-utils.ts#L74

Please support @typespec/openapi3 in scope

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Read the [docs](https://azure.github.io/typespec-azure/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wanlwanl** [comment]
@timotheeguerin 
1. I'm trying set @clentname with scope. java emitter and autorest emitter has different behaviors as you share screen before. When openAPI's version increases inthe future, I feel like we might need to customize some where. e.g. OpenAI.Assistants used tcgc and emit OAS3. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/ai/OpenAI.Assistants/client.tsp .
2. No, I tried: https://github.com/Azure/typespec-azure/pull/1751
I got
```
AssertionError: Expected values to be strictly equal:
+ actual - expected

+ 'Test'
- 'TestOAS3'
       ^

Expected: "TestOAS3"
Received: "Test"
```

**Comment by timotheeguerin** [comment]
For `2.` I mean this should be how it works, and it was supposed to work that way with tcgc so they definitely have a bug if it doesn't.

For `1.` there is 2 reason why it doesn't make sense to support in openapi3:
1. this is an azure library, none of the `@typespec/` packages should be using them
2. OpenAPI doesn't describe client, it describe the service contract. There is nowhere to put a client name in the spec apart from using `x-` extensions and we explicitly don't want the openapi3 emitter to have any of those. Autorest swagger emits it because it target the augmented version of swagger 2.0 meant for autorest.

**Comment by wanlwanl** [comment]
Thanks for the explain. I thought we need to keep the same behavior to autorest swagger.
