### ISSUE TITLE
SdkDurationType.writeType is too broad

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#26]
`wireType` is defined as `SdkBuiltInType` which contains types that would never be applicable. This should be narrowed to a subset of the applicable types.

**Comment by iscai-msft** [comment]
we don't have specific types for strings or integers, they're just possible kinds for `SdkBuiltInType`. I'm going to close this issue because I think the fix is more effort than it's worth, considering that we'd have to do a redesign. If you still think it's worth looking into @jhendrixMSFT , can you reopen the issue? Thanks!
