### ISSUE TITLE
[Bug] ArmResourceListByParent does not respect operation name but hard code to ListByResourceGroup.

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#37]
**Describe the bug**
[When using ArmResourceListByParent template, operation id is hard coded to _ListByResourceGroup](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgpAYXJtUHJvdmlkZXJOYW1lc3BhY2UKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zb8guSHViQ2xpZW50IiwKICDnAS06ICIyMDIxLTEwLTAxLXByZXZpZXciLAp9KQpAZG9jKMhFIOgAiiDITyDmAQptZW50IEFQSS4iKQpAdXNlRGVwZW5kZW5jeSj1AMPoAP1zLnYxXzBfUMZyXzEp5QDaQ29tbW9u5AEpc8co10bLKctSNSkKbugBFCBNaWNyb3NvZnQu8gEJ5AFJ5QDfQSDSHSDoAe0iKQptb2RlbCBFbXBsb3llZSBpcyBUcmFja2Vk6ACRPMgcUHJvcGVydGllcz4g5AGGxmDkAaMgb2YgZccmIinEG3BhdHRlcm4oIl5bYS16QS1aMC05LV17MywyNH0kxiNrZXkoIsg2xEbJOmjECHNlZ%2BQBesojc8Ug5AD%2BOiBzdHLlAlx96ADm6QDAcOkApfEA3OoAwOsAv0Fn8gC%2BYWdlPzogaW50MzI7CskqQ2l0edErY2l0eT%2FqAJDJLVByb2ZpbNJbQGVuY29kZSgiYmFzZTY0dXJsxRdwxi8%2FOiBieXRlc8ZJdmlzaWJpbGl0eSgicmVhZMZBxV9UaGUgc3RhdHVzxGJ0aGUgbGFzdCDkAOBhdGlvbuQCrMVWxETlA4hTdGF0xGDlAgbMFOsBRcRWzDTFY%2BUAxGHpAjLEWkBscm%2FEPHVzCmVudW3SVOUBYC4u6QLU0SEs6gEqxHXIXeQCfmJlxHrpAIdl5gD3zELbPXVwZGF05AUfxDRVxw3fbWcgZGVsZXTHaUTEDNs1Y3Jl5ADhcmVxdWVzdCBoYcRFZW4gYWNjZXDIRUHHDSzkAVxpbnRlcmbkA7BP6AGfcyBleHRlbmRz9gUFLsspe%2BQBnmFybcgjyhvLWegC4uYC2WdldOQA3EHKNVJlYWTpA8c%2BO%2BQCuOUAx09y5QEk5QELyy9DzR1Bc3luY84%2B5QFn0DZQYXRjaFPMLCzzA3vFQOYBcc9A5QF6Zc1BxS1saXN0QnlTdWJzY3JpcOQA%2B8c5TNEZzDkKICAvL8U9VOQBqWlzIG5vdOcB8XVzZWQux1vIHusAisZZUGFyZW50zFN9Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Expected behavior**
`listTest` should be correctly set in operation_id.

**Comment by markcowl** [comment]
There are actually template parameters that [set this](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgpAYXJtUHJvdmlkZXJOYW1lc3BhY2UKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zb8guSHViQ2xpZW50IiwKICDnAS06ICIyMDIxLTEwLTAxLXByZXZpZXciLAp9KQpAZG9jKMhFIOgAiiDITyDmAQptZW50IEFQSS4iKQpAdXNlRGVwZW5kZW5jeSj1AMPoAP1zLnYxXzBfUMZyXzEp5QDaQ29tbW9u5AEpc8co10bLKctSNSkKbugBFCBNaWNyb3NvZnQu8gEJ5AFJ5QDfQSDSHSDoAe0iKQptb2RlbCBFbXBsb3llZSBpcyBUcmFja2Vk6ACRPMgcUHJvcGVydGllcz4g5AGGxmDkAaMgb2YgZccmIinEG3BhdHRlcm4oIl5bYS16QS1aMC05LV17MywyNH0kxiNrZXkoIsg2xEbJOmjECHNlZ%2BQBesojc8Ug5AD%2BOiBzdHLlAlx96ADm6QDAcOkApfEA3OoAwOsAv0Fn8gC%2BYWdlPzogaW50MzI7CskqQ2l0edErY2l0eT%2FqAJDJLVByb2ZpbNJbQGVuY29kZSgiYmFzZTY0dXJsxRdwxi8%2FOiBieXRlc8ZJdmlzaWJpbGl0eSgicmVhZMZBxV9UaGUgc3RhdHVzxGJ0aGUgbGFzdCDkAOBhdGlvbuQCrMVWxETlA4hTdGF0xGDlAgbMFOsBRcRWzDTFY%2BUAxGHpAjLEWkBscm%2FEPHVzCmVudW3SVOUBYC4u6QLU0SEs6gEqxHXIXeQCfmJlxHrpAIdl5gD3zELbPXVwZGF05AUfxDRVxw3fbWcgZGVsZXTHaUTEDNs1Y3Jl5ADhcmVxdWVzdCBoYcRFZW4gYWNjZXDIRUHHDSzkAVxpbnRlcmbkA7BP6AGfcyBleHRlbmRz9gUFLsspe%2BQBnmFybcgjyhvLWegC4uYC2WdldOQA3EHKNVJlYWTpA8c%2BO%2BQCuOUAx09y5QEk5QELyy9DzR1Bc3luY84%2B5QFn0DZQYXRjaFPMLCzzA3vFQOYBcc9A5QF6Zc1BxS1saXN0QnlTdWJzY3JpcOQA%2B8c5TNEZzDkKICAvL8U9VOQBqWlzIG5vdOcB8XVzZWQux1vIHusAisZZUGFyZW50PAogICDpAMjkBlgg9wG1Rm91buQCceQFqEJhc2VQYXJhbWV0ZXJz6gCXxkAixHTlBqTIDAogID7kA4k%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by markcowl** [comment]
I think deferring to 'name' makes sense, but we should then have a linting rule that promotes the `listBy` naming, because these list operations can be combined in client generation.

**Comment by markcowl** [comment]
You can do this with a projectedName decorator - this is necessary because we are using a decorator to enforce a particular naming pattern,  here is a [sample playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgpAYXJtUHJvdmlkZXJOYW1lc3BhY2UKQHNlcnZpY2UoewogIHRpdGxlOiAiQ29udG9zb8guSHViQ2xpZW50IiwKICDnAS06ICIyMDIxLTEwLTAxLXByZXZpZXciLAp9KQpAZG9jKMhFIOgAiiDITyDmAQptZW50IEFQSS4iKQpAdXNlRGVwZW5kZW5jeSj1AMPoAP1zLnYxXzBfUMZyXzEp5QDaQ29tbW9u5AEpc8co10bLKctSNSkKbugBFCBNaWNyb3NvZnQu8gEJ5AFJ5QDfQSDSHSDoAe0iKQptb2RlbCBFbXBsb3llZSBpcyBUcmFja2Vk6ACRPMgcUHJvcGVydGllcz4g5AGGxmDkAaMgb2YgZccmIinEG3BhdHRlcm4oIl5bYS16QS1aMC05LV17MywyNH0kxiNrZXkoIsg2xEbJOmjECHNlZ%2BQBesojc8Ug5AD%2BOiBzdHLlAlx96ADm6QDAcOkApfEA3OoAwOsAv0Fn8gC%2BYWdlPzogaW50MzI7CskqQ2l0edErY2l0eT%2FqAJDJLVByb2ZpbNJbQGVuY29kZSgiYmFzZTY0dXJsxRdwxi8%2FOiBieXRlc8ZJdmlzaWJpbGl0eSgicmVhZMZBxV9UaGUgc3RhdHVzxGJ0aGUgbGFzdCDkAOBhdGlvbuQCrMVWxETlA4hTdGF0xGDlAgbMFOsBRcRWzDTFY%2BUAxGHpAjLEWkBscm%2FEPHVzCmVudW3SVOUBYC4u6QLU0SEs6gEqxHXIXeQCfmJlxHrpAIdl5gD3zELbPXVwZGF05AUfxDRVxw3fbWcgZGVsZXTHaUTEDNs1Y3Jl5ADhcmVxdWVzdCBoYcRFZW4gYWNjZXDIRUHHDSzkAVxpbnRlcmbkA7BP6AGfcyBleHRlbmRz9gUFLsspe%2BQBnmFybcgjyhvLWegC4uYC2WdldOQA3EHKNVJlYWTpA8c%2BO%2BQCuOUAx09y5QEk5QELyy9DzR1Bc3luY84%2B5QFn0DZQYXRjaFPMLCzzA3vFQOYBcc9A5QF6Zc1BxS1saXN0QnlTdWJzY3JpcOQA%2B8c5TNEZzDkKICAvL8U9VOQBqWlzIG5vdOcB8XVzZWQux1vIHusAisZZUGFyZW50zFPkAYtAcHJvamVjdGVk5ASzKMgecy7ITCwgImPnBoUgIsgVIik7Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Comment by markcowl** [comment]
The decorator here is a legacy from when only interface templates were avaiable, and not operation templates.  We should likely update the existing interfaces to use this decorator, update any existing specs to specify the correct name in their usage of the operation templates, and remove the decorator from the operation templates altogether.

We *may* want to also add a linting rule to suggest correct naming patterns.
