### ISSUE TITLE
Give different arm base model definition for different common-type version

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#377]
Problem derived from: https://github.com/Azure/typespec-azure-pr/issues/3766.
Currently, we have decorator to annotate which common-type version we use for a service. But when compile direct from tsp, we will get the same arm base model definition for all common-type versions. Since Python, Go, JS use the direct information from compiler to generate models, the generated code will be wrong.

**Comment by markcowl** [comment]
@tadelesh @MaryGao  We should always be using the TypeSpec definition.  AFAIK, because we have a minimum version for many types, there aren't any significant differences between the TypeSpec type definition and the corresponding generated code from Swagger. This was verified by one of our devs before that feature was introduced

**Comment by markcowl** [comment]
@tadelesh @ArthurMa1978 Please provide an instance of a spec that is blocked by this issue

**Comment by tadelesh** [comment]
![image](https://github.com/Azure/typespec-azure/assets/1726438/2fdd3d3e-6fdf-476d-940c-ede26e849555)
That's the only one I know learning from .NET codegen brownbag. I'm not sure if there are any other breakings.

**Comment by allenjzhang** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json#L387 and https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L653-L656

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json#L347-L368 and https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L131C7-L149

**Comment by allenjzhang** [comment]
Describe the breaking change
Fully enabled versioned common-type representations in TypeSpec ARM Library.



Back-compat design to avoid immediate breaking
  - Leveraged smart default and existing 1@armCommonType` decorator for version selection
  - 

Link to detailed breaking design
Link:

Impact
This change affecting some generated swagger textually:
- Some description text changes
 - Some service spec will need to add explicit ARM comment type version reference
 - Some service spec output swagger will now redirected to the common type $ref rather than TypeSpec definitions
```
   -   "$ref": "#/definitions/Azure.ResourceManager.PrivateEndpointConnection"
   +  "$ref": "../../../../../common-types/resource-management/v5/privatelinks.json#/definitions/PrivateEndpointConnection"
``` 

 - [X] ARM
 - [ ] Data-plane
 - [X] Existing specs: 11 specs
 - [ ] New specs
 - [ ] Emitters
 - [ ] SDK

Targeted Sprint
Sprint: June

Additional information
