### ISSUE TITLE
Discrepancy of generation from tsp and swagger for resource name property

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#378]
Current tsp, we define a resource `name` property in the final resource model, not inherit it from the base resource model. This will cause the `name` property in the generated code for JS and Python to be breaking.

For example, a `FooResource` defined as:
https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-resource-manager/test/resource.test.ts#L49-L56
It is sourced from `TrackedResource` template:
https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-resource-manager/lib/models.tsp#L17-L25
Which is derived from `TrackedResourceBase` model:
https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L49-L55
Which is derived from `ArmResource` model:
https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L22-L37

You could see `name` property is defined in `FooResource`, not in `ArmResource`.

But with swagger common-types, the name is defined in the root `Resource` model:
https://github.com/Azure/azure-rest-api-specs/blob/84849e5293de3a8e01cbdde13b2d7086d3fb34d6/specification/common-types/resource-management/v5/types.json#L9-L37

**Comment by tadelesh** [comment]
One real issue from service team: https://github.com/Azure/azure-rest-api-specs/pull/27565#discussion_r1518977192

**Comment by markcowl** [comment]
@tadelesh I don't think the referenced spec is actually blocked by this, because it cannot use the resource templates in any case, due to their inheriance form TrackedResource or ProxyResource.  The only way to represent this API without breaks is to use a custom-defined resource type, [as shown in this playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyCNzdXBwcmVzc%2F8Cq29yZS9jb21wb3NpdGlvbi1vdmVyLWluaGVyaXRhbmNlIiAiZXhpc3TkAjxhcGkiCm1vZGVsIEVtcGxveWVlIGV4dGVuZHP9AacuQXJt6QJU6AGHUlAt5ACIaWZpYyBwcm9wZXJ0aWXlAbcgyxA%2FOslrUMkVO%2BQBBmFsaWFzyh1hcmFtZXRlciA9yWLkAkQgb2YgdGhlIGXHKMZgQHBhdGjECHNlZ%2BQC1SgiyCBzIuQBe8gO5ALYOiBzdHLlA1N95wJvVGhlIGJhc2XqAXDkAVXEWuYBHPQA7uQAhMkvaWTELSAgaWTKXdQo5QDBxSrECt4s6ACDIMUKyiznAjDpAbDuAWvuAc3qAWLpALhBZ%2BUBQ%2B4BP2FnZT86IGludDMy6QCNQ2l0edIqY2l0eT%2FxALlQcm9maWzTWUBlbmNvZGUoIuQBXzY0dXJs5QGPcMYwPzogYnl05AH%2Fx0jkAYlzdGF0dXPoAedsYXN0IOQAxWHkAs3lBKggIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUFL1N0YXTEX%2BUCtMwU6QFAxGvMMsV45QDCYekBhMVvQGxyb8Q7dXPmBH%2FRU%2BUBWy4u6QQK0SEs7ADfyFwgaXMgYmXEeekAhmXnAkbMQdk8dXBkYeUDxMUzVccO32tkZWxldMhnRMQN2TRjcmXkANxyZXF1ZXN0IGhhxERlbiBhY2NlcMlEQccO6QTH6QKXbW92yj7pAplNb3ZlUscV6AKSxHdtb3bkAKBmcm9tIGxvY%2BUB7cZixBPxAnDLM3RvzzF0b%2FoDLOcAlXNwb25z6wPg5gCWxxbsAJfuAozFPsVkxnzmAhbNbmludGVyZuQG5k%2FoArRz6QVS9gYxyyl7fQrlB4bII8oby1noAM3mA9NnZXTkAd%2FrBKJSZWFkPMglLCDpBUhzID3yBV0%2BO%2BQD1OUB609y5QJF5QIuy09Dxx1SZXBsYWNlQXN5bmM8CiAgIMlNLMUO3mgKICDFa%2BUCtshjQ3VzdG9tUGF0Y2hT11bfZNVk5gLl7wDH5QLtZVdpdGhvdXRPa%2F8Ax99jIGxpc3RCechcR3JvdXDPcEzFIlBhcmVudOkBjss8U3Vic2NyaXDlArjGO8YzzBnMOegFvyBzYW1wbOsDqWFjxUR0aGF05gKi6QWCdG8gZGlmZmXkAITvAyXFKe4AskHFSPgBiesDucwR5gM0%2FwE76wE78ADGSEVBROoF3%2BQAsmNoZWNr6gDe5QirZW7mCQMgxh5FyRTvAqvNHf8B3vkAo30K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D)

Note that this *will* be a problem for new specs that were originally introduced in TypeSpec, or any specs that use resource types that directly inherit from ProxyResource of TrackedResource (a small list).  This problem should be addressed by this issue: https://github.com/Azure/typespec-azure-pr/issues/3873

**Comment by tadelesh** [comment]
> @tadelesh I don't think the referenced spec is actually blocked by this, because it cannot use the resource templates in any case, due to the resource type inheriance form TrackedResource or ProxyResource. The only way to represent this API without breaks is to use a custom-defined resource type, [as shown in this playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn3mAPNB6AD16wEOIOgCTeQAyCNzdXBwcmVzc%2F8Cq29yZS9jb21wb3NpdGlvbi1vdmVyLWluaGVyaXRhbmNlIiAiZXhpc3TkAjxhcGkiCm1vZGVsIEVtcGxveWVlIGV4dGVuZHP9AacuQXJt6QJU6AGHUlAt5ACIaWZpYyBwcm9wZXJ0aWXlAbcgyxA%2FOslrUMkVO%2BQBBmFsaWFzyh1hcmFtZXRlciA9yWLkAkQgb2YgdGhlIGXHKMZgQHBhdGjECHNlZ%2BQC1SgiyCBzIuQBe8gO5ALYOiBzdHLlA1N95wJvVGhlIGJhc2XqAXDkAVXEWuYBHPQA7uQAhMkvaWTELSAgaWTKXdQo5QDBxSrECt4s6ACDIMUKyiznAjDpAbDuAWvuAc3qAWLpALhBZ%2BUBQ%2B4BP2FnZT86IGludDMy6QCNQ2l0edIqY2l0eT%2FxALlQcm9maWzTWUBlbmNvZGUoIuQBXzY0dXJs5QGPcMYwPzogYnl05AH%2Fx0jkAYlzdGF0dXPoAedsYXN0IOQAxWHkAs3lBKggIEB2aXNpYmlsaXR5KCJyZWFkyFXEGOUFL1N0YXTEX%2BUCtMwU6QFAxGvMMsV45QDCYekBhMVvQGxyb8Q7dXPmBH%2FRU%2BUBWy4u6QQK0SEs7ADfyFwgaXMgYmXEeekAhmXnAkbMQdk8dXBkYeUDxMUzVccO32tkZWxldMhnRMQN2TRjcmXkANxyZXF1ZXN0IGhhxERlbiBhY2NlcMlEQccO6QTH6QKXbW92yj7pAplNb3ZlUscV6AKSxHdtb3bkAKBmcm9tIGxvY%2BUB7cZixBPxAnDLM3RvzzF0b%2FoDLOcAlXNwb25z6wPg5gCWxxbsAJfuAozFPsVkxnzmAhbNbmludGVyZuQG5k%2FoArRz6QVS9gYxyyl7fQrlB4bII8oby1noAM3mA9NnZXTkAd%2FrBKJSZWFkPMglLCDpBUhzID3yBV0%2BO%2BQD1OUB609y5QJF5QIuy09Dxx1SZXBsYWNlQXN5bmM8CiAgIMlNLMUO3mgKICDFa%2BUCtshjQ3VzdG9tUGF0Y2hT11bfZNVk5gLl7wDH5QLtZVdpdGhvdXRPa%2F8Ax99jIGxpc3RCechcR3JvdXDPcEzFIlBhcmVudOkBjss8U3Vic2NyaXDlArjGO8YzzBnMOegFvyBzYW1wbOsDqWFjxUR0aGF05gKi6QWCdG8gZGlmZmXkAITvAyXFKe4AskHFSPgBiesDucwR5gM0%2FwE76wE78ADGSEVBROoF3%2BQAsmNoZWNr6gDe5QirZW7mCQMgxh5FyRTvAqvNHf8B3vkAo30K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D)
> 
> Note that this _will_ be a problem for new specs that were originally introduced in TypeSpec, or any specs that use resource types that directly inherit from ProxyResource of TrackedResource (a small list). This problem should be addressed by this issue: [Azure/typespec-azure-pr#3873](https://github.com/Azure/typespec-azure-pr/issues/3873)

Then how should emitter deal with the `ArmResource` model in different namespace? In swagger, we will ask service team to choose either use common types or use self-defined base resource models to prevent duplicate schema. I'm afraid it will happen again in TypeSpec?

**Comment by allenjzhang** [comment]
Pending design issue:

https://github.com/Azure/typespec-azure-pr/issues/3873

**Comment by allenjzhang** [comment]
https://github.com/Azure/typespec-azure/pull/661 Merged
