### ISSUE TITLE
Add decorator to make a parameter to client level

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#493]
In swagger, we have `x-ms-parameter-location` [extension](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-parameter-location) to set a parameter to client level. We should also support it in TCGC as a client customization. The main usage scenario is for [ARM](https://github.com/Azure/azure-rest-api-specs/blob/8d1d3d29cdbe03f95a9b4c0ec6bb2221f1c44bde/specification/common-types/resource-management/v4/types.json#L626).

**Comment by qiaozha** [comment]
Is there a case that we need a not-subscriptionId parameter to be client level? I wonder if we should limit the scope of this customization to subscripitonId parameter, and ARM only? 

I have handled so many cases where service team abused of x-ms-parameter-location and causes problems for us because we honor this value, and java completely ignore x-ms-parameter-location if it's a not-subscriptionId parameter.

**Comment by tadelesh** [comment]
@qiaozha ref: https://github.com/Azure/typespec-azure/issues/914, we got customer ask for data plane for such feature.

**Comment by qiaozha** [comment]
Interesting, can we at least set the default value into method level ?

**Comment by tadelesh** [comment]
> Interesting, can we at least set the default value into method level ?

sure.

**Comment by lmazuel** [comment]
See https://github.com/Azure/typespec-azure/issues/914
