### ISSUE TITLE
Swagger emitter makes up new name for the same model with different schemas

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#688]
**Background:**
We have some customers that already have their typespec. However, our generators still have some limitations so that we cannot support typespec input. So these customers have to generate swagger first from swagger emitter and then call our generator with swagger input. We expect when our generator is ready to accept typespec input, their original typespec generates same SDK, which means the swagger generated from typespec should be equivalent.

**Problem:**
There are several scenarios under which the model names in the generated swagger are different from original typespec:
1. When model has visibility decorator. [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7DQoNCnVzaW5nIFR5cGVTcGVjLkh0dHDFGEBkb2MoIlRlc3QgZm9yIMQ6IG9mIHVuaW9uLiIpDQpAc2VydmVyKA0KICAie0VuZHBvaW50fS9sYW5ndWFnZSIsxRpMxw8gU2Vydmljxxd7xAUgIMg2OskKxR59DQrIYWljZSjFLXRpdGxlOiAiTWljcm9zb2Z0IENvZ25pdGl2ZSDQZCAtIEFuYWx5emUgVGV4dCBBdXRob3JpbmfGfXZlcnNpb246ICIyMDLDnzItMDUtMTUtcHJldmlld8QkfcR%2FdXNlxDkoQXBpS2V5xAs8xgtMb2NhdOQBB2hlYWRlciwgIk9jcC1BcGltLVN1YnNjcmlwxB8tS2V5Ij7ESnJvdXRlKCIvYegAiC9h5gCfLXRleHQv5AFObmFtZXNwYWNlIE1vZGVscy5WaXNpYmlsaXR5LkF1dG9tYXRpY%2BUBmS8vIFRPRE86IFVzZSB0aGUgY29tbW9uIHBhcmFtZXRlcuYBsGhpc%2BkBxWhlIGXnAWAgdG8gdXNl5QHCc2NhbGFy6QF7IGV4dGVuZHMgc3TkAKTrAgZPdXRwdXQgbeQAmiB3aXRoIHbpAJ4gcHJvcGVydGllc8VVxiXqAL7lAM%2FmAfDGTVJlcXVpcmVkx2csIGlsbHVzdHJhdOQCiWEgcmVhZG9ubMlZecVXICBAynQoIsQlxhfEClByb3A67AC30WxpbnQzMtFrcXVlct5oxSLGGMULxmrFTtZp5gCFW13RbGNyZWF0Zd1txiPGGcYM7ADZW13WcuUAjdNxdXBk33EixiPGGcYM6wDg2HBib29s0W1kZWxl323GI8YZxgzGbcRQZWFuOw0KfeoCciIiDQpHZW5lcuQAw2FuZCByZWNl5APrb%2FECi%2FACMOQCiQ0KRXhwZWN05QEfxDBib2R5Og0KYGBganNvbg0K5QKQ6wHSMTIz5AP3xSLkAIbJP3Jlc3BvbnNl1kLqAn0iYWJj5QQ6x0MiIuUFJGdldA0Kb3AgZ2V05QMJKEDESOYAlTrwAyYp0RLrA4TuARJiZCBzZW5kIO8BDHdyaXRlL%2B4Ca%2F8BEP8BEOwAzeQE7%2BUAzsQJ%2FwDP5gDPT2tS5wFA%2FwDK%2FQDKL%2B4Cy%2F8A0esA0ewDRVsiZm9vIiwgImJhciJd5QYI7ALzWzEsIDLEF%2B8A9HB15gHBcHX%2FAcHnAPJ2b2lk%2FwDs9wDs%2FwDl%2BQDl%2FwDG5gDGYXRjaOYAyMQK%2FwDK%2FwDK%2FwDK%2FwKA%2FwGv%2BQGv8ADSb3PnAZlvc%2F8Bmv8A0P8A0P8A0PwA0OwE5nRydWXyAMbGIuUAyMYL%2FwDK6wDK&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)
2. Models in patch operations. [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn0KCm1vZGVsIEFzc2V0RW5kcG9pbnRQcm9maWxlIGlzIFRyYWNrZWTIaTzUKFByb3BlcnRpZXM%2B5QEXQGRvYygixSogyCvkAf3FVOQBiyBwYXJhbWV0ZXIuIuUA5GtleSgiYdNb5AILxiNzZWfkAjHWJ3PGJHBhdHRlcm4oIl5bYS16MC05XccILV0qyBIkyStoxAhtaW5MZW5ndGgoM8UYbWF4xxA2xRHkAK86IHN0cuUDB%2F0BL%2BoBB%2BsBBkdsb2JhbGx5IHVuaXF1ZSwgaW1tdXRhYmxlLCBub24tcmV1c8QOIGlk5gEMdXVpZD%2FKcslJVGhlIGxvY2FsIHZhbGlkIFVSSSDkA%2FppZnnkA4l0aGUgbmV0d29yayBhZGRyZXNzL0ROU%2BYBb29mIGEgc291dGhib3VuZCBkZeQDVS4gxFRzY2hl5gGSdMQoxEh0YXJnZXRBxkbLaeQA2sUgeXDFVMQMzEthZGRpdGlvbmFsQ29uZmlndXJhxA8gZmllbGQgaG9sZHMgZnVydGhlciBjb25uZWN0b3LGTsdhY8QYyjrmARLtAI86IHVybOsBF0RlZmlu5wCYY%2BUEByBhdXRoZW50aWPGfm1lY2hhbmlzbSB0b8Un5ARU6AJ6dXNlckHNMD86IFXRFctx5AQeYWluc%2BgAwml2aXR57wDF6wDl6wEHKGUuZy4gT1BDIFVBLCBNb2RidXMsIE9OVklGKeYAjvcBQesCD30KCusA%2BMUt6AGK%2FwD%2B8gD%2B5gLK8gDt6wK%2B7AFexC%2FERcthZcUZ5AFE8ACFdM9sICAvLyBEZWZhdWx0xkppcyBD5AMuZsVJCiDFFvMC%2BOwAg8Rq5QLRYW5kIHBhc3N3b3JkIHJlZmVyZW5jZXMgd2hlbuUA0sQmUMghxDfxARjnAIRzZWxlY3Rl6AN9zztDcmVkxDVhbHP0A5TtAn3qAM3qAJLmAJHrAOj%2FAIzsAIx4NTA59gCAfQoKaW50ZXJm5AbRT3Bl5gImcyBleHRlbmRz9geVLsspe%2BQCR2FybcgjyhvLWUVtcGxveWXnBM4vL2NyZWF0ZU9yVXBk5ADJaXMgQcpCQ8cdUmVwbGFjZUFzeW5j9QYsPjvkAWfUQ1BhdGNoU9g4LP8Fcz7kARc%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D) You could see the body type changed to `AssetEndpointProfileUpdate` as well as its nested models.

**Expected behavior:**
From this [additional trial](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CnVzaW5nIEh0dHA7CkBmcmllbmRseU5hbWUoIntuYW1lfVBhZ2UiLCBUKQptb2RlbCDEEDxUPiB7CiAgc2l6ZTogaW50MzI7CiAgaXRlbTogVFtdOwp9CscvVXNlcsUsaWQ%2FOnN0cmluZ8QrxFvLEC8vIEB2aXNpYmlsaXR5KCJkZWxldGUiKQogIHRlc3TKKn0KCm9wIGdldCgpOuYAi8RhPjsKCkBwYXRjaMQexQkoQGJvZHkgxAU65QCFKTp2b2lkOwoKxGzGYMQLb3Agxg3MMcsw&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D) of "a model with all the optional properties in a patch operation", which don't have any made-up name, I could understand the swagger emitter produces new name because of there are more than one schema needed for the same model. But IMO we should keep the name unchanged and figure out another way to handle the different representation of the same model.

**Comment by markcowl** [comment]
MO, this is by design.  ArmResourcePatch creates a set of schema that are compatible with current RPC guidelines on PATCH.  Many legacy APIs used older guidelines, or predated any real enforcement on how PATCH worked.  Additionally, there are no controls over how types created from metadata are named (for which there is an existing design issue).
 
For ARM brownfield APIs, though, most APIs should be using ArmCustomPatch, which allows you to specify your own request body schema, [here is an example playground showing this](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn0KCm1vZGVsIEFzc2V0RW5kcG9pbnRQcm9maWxlIGlzIFRyYWNrZWTIaTzUKFByb3BlcnRpZXM%2B5QEXQGRvYygixSogyCvkAf3FVOQBiyBwYXJhbWV0ZXIuIuUA5GtleSgiYdNb5AILxiNzZWfkAjHWJ3PGJHBhdHRlcm4oIl5bYS16MC05XccILV0qyBIkyStoxAhtaW5MZW5ndGgoM8UYbWF4xxA2xRHkAK86IHN0cuUDB33mAiJQYXRjaCBib2R5IGZvcusBPOoBOyov%2BwFZVXBkYXRl5QEsLi4u9gHLRm91bmRhdOUBwkFybVRhZ3PnAWh5OwrnAnxSUC3kA%2F1pZmljIHDGHWll5QKsIMsQPzr1AIXHTmllc%2BkA2FJQLeQD%2BtNQ%2BgDMykfrAfxHbG9iYWxseSB1bmlxdWUsIGltbXV0YWJsZSwgbm9uLXJldXPEDiBpZOYCAnV1aWQ%2F6gFoyUlUaGUgbG9jYWwgdmFsaWQgVVJJIOYA83nkBH90aGUgbmV0d29yayBhZGRyZXNzL0ROU%2BYCZW9mIGEgc291dGhi5AFMIGRl5ARLLiDEVHNjaGXmAoh0xCjESHRhcmdldEHGRstp5ADaxSB5cMVUxAzMS2FkZGnkAadhbENvbmZpZ3Vy5QG2IGZpZWxkIGhvbGRzIGZ1cnRoZXIgY29ubmVjdG9yxk7HYWPEGMo65gES7QCPOiB1cmzrARdEZWZpbucAmGPlBP0gYXV0aGVudGljxn5tZWNoYW5pc20gdG%2FFJ%2BQFSugDcHVzZXJBzTA%2FOiBV0RXLceQFFGFpbnPoAMJpdml0ee8AxesA5esBByhlLmcuIE9QQyBVQSwgTW9kYnVzLCBPTlZJRinmAI73AUHrAg99CgrrAPjFLegBiv8A%2FvIA%2FuYCyvIA7esCvuwBXsQvxEXLYWXFGeQBRPAAhXTPbCAgLy8gRGVmYXVsdMZKaXMgQ%2BQDLmbFSQogxRbzAvjsAIPEauUC0WFuZCBwYXNzd29yZCByZWZlcmVuY2VzIHdoZW7lANLEJlDIIcQ38QEY5wCEc2VsZWN0ZegDfc87Q3JlZMQ1YWzkBDz9AJxj6gDN6gCS5gCR6wDo%2FwCM7ACMeDUwOfYAgH0KCmludGVyZuQHx09wZeYCJnMgZXh0ZW5kc%2FYIiy7LKXvkAkdhcm3II8oby1lFbXBsb3ll5wTOLy9jcmVhdGVPcucFs2lzIEHKQkPHHVJlcGxhY2VBc3luY%2FUHIj475gZ05wb2VmlzaWJpbGl0eSgicmVhZOYBhsxiQ3VzdG9t5QZoU8RVCiAgIPUFfyzZGuYAsgogID7kATw%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D) .  You may need to change the parameterVisibility for the operation if there are required properties in your PATCH schema.

**Comment by XiaofeiCao** [comment]
Hi @markcowl ,

If I'm understanding correctly, there's a new guideline of the PATCH model schema name right? May I ask which guideline are you referring to?

On the other hand, if we were to follow this new guideline for all SDKs, I think we should enforce this in some common places, e.g. compiler or TCGC, instead of this implict behavior that exists only in `typespec-autorest` :(

**Comment by allenjzhang** [comment]
This problem is not new. Prior to TypeSpec, service teams all have different approaches in swagger, some use the root model while some use update model for Patch. I assume you reproduce that faithfully at that time as well, right?

**Comment by tadelesh** [comment]
let's use [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7CgovKiogQ29udG9zbyDIHiBQcm92aWRlciDmAJ5tZW50IEFQSS4gKi8KQGFybcggTmFtZXNwYWNlCkBzZXJ2aWNlKHsKICB0aXRsZTogIsdYyC5IdWJDbGllbnQiLAp9KQpA5wFgZWQo5wDBcykKbshSIE1pY3Jvc29mdC7SR%2B8AuEFQSSDHTXPkAKNlbnVtIMhUIOQAksQuMjAyMS0xMC0wMS1wcmV2aWV3yDXENCAgQHVzZURlcGVuZGVuY3ko9QEx6AFrcy52MV8wX1DGSF8xKcRAYXJtQ29tbW9u5AGZc8cq10jLKctUNcRIYPIAqWAsCn0KCm1vZGVsIEFzc2V0RW5kcG9pbnRQcm9maWxlIGlzIFRyYWNrZWTIaTzUKFByb3BlcnRpZXM%2B5QEXQGRvYygixSogyCvkAf3FVOQBiyBwYXJhbWV0ZXIuIuUA5GtleSgiYdNb5AILxiNzZWfkAjHWJ3PGJHBhdHRlcm4oIl5bYS16MC05XccILV0qyBIkyStoxAhtaW5MZW5ndGgoM8UYbWF4xxA2xRHkAK86IHN0cuUDB%2F0BL%2BoBB%2BsBBkdsb2JhbGx5IHVuaXF1ZSwgaW1tdXRhYmxlLCBub24tcmV1c8QOIGlk5gEMdXVpZD%2FKcslJVGhlIGxvY2FsIHZhbGlkIFVSSSDkA%2FppZnnkA4l0aGUgbmV0d29yayBhZGRyZXNzL0ROU%2BYBb29mIGEgc291dGhib3VuZCBkZeQDVS4gxFRzY2hl5gGSdMQoxEh0YXJnZXRBxkbLaeQA2sUgeXDFVMQMzEthZGRpdGlvbmFsQ29uZmlndXJhxA8gZmllbGQgaG9sZHMgZnVydGhlciBjb25uZWN0b3LGTsdhY8QYyjrmARLtAI86IHVybOsBF0RlZmlu5wCYY%2BUEByBhdXRoZW50aWPGfm1lY2hhbmlzbSB0b8Un5ARU6AJ6dXNlckHNMD86IFXRFctx5AQeYWluc%2BgAwml2aXR57wDF6wDl6wEHKGUuZy4gT1BDIFVBLCBNb2RidXMsIE9OVklGKeYAjvcBQesCD30KCusA%2BMUt6AGK%2FwD%2B8gD%2B5gLK8gDt6wK%2B7AFexC%2FERcthZcUZ5AFE8ACFdM9sICAvLyBEZWZhdWx0xkppcyBD5AMuZsVJCiDFFvMC%2BOwAg8Rq5QLRYW5kIHBhc3N3b3JkIHJlZmVyZW5jZXMgd2hlbuUA0sQmUMghxDfxARjnAIRzZWxlY3Rl6AN9zztDcmVkxDVhbHP0A5TtAn3qAM3qAJLmAJHrAOj%2FAIzsAIx4NTA59gCAfQoKaW50ZXJm5AbRT3Bl5gImcyBleHRlbmRz9geVLsspe%2BQCR2FybcgjyhvLWUVtcGxveWXnBM4vL2NyZWF0ZU9yVXBk5ADJaXMgQcpCQ8cdUmVwbGFjZUFzeW5j9QYsPjvkAWfUQ1BhdGNoU9g4LP8Fcz7kARc%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%5D%7D%7D) as an example, there are two kinds of model separation logics:
1. separate by template, in the example, for ArmResourcePatchSync , we will have a AssetEndpointProfileUpdate model created. this is defined in template and for any emitter, we could get the model from compiler
2. separate by emitter logic, in the example, autorest emitter will generate UserAuthenticationUpdate since it has required properties. this is implemented by different emitters themselves.
i believe we do not discuss them separately in the meeting. imo, for 1, we should leave as it is. for 2, if we could have consensus across all languages' sdk that we need do it, we could opt it in tcgc, otherwise i don't like such implicitly behavior. and since you all think it is a client behavior, why we do this in openapi and autorest emitter, if not, why http library do it for all emitter?

**Comment by markcowl** [comment]
Clowing this issue in favor of https://github.com/Azure/typespec-azure/issues/859
