### ISSUE TITLE
Removing dependency on `typespec-autorest` from arm package

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/typespec-azure#697]
- Provide the mapping in arm as an JS object that autorest can consume 
```
export function getCommonType(model: Model): string | undefined;
```

**Comment by markcowl** [comment]
est: 5

**Comment by markcowl** [comment]
**Describe the breaking change**
The ARM library removed its dependency on typespec-autorest, as was required for MPG support.  Any specs that use decorators from the Autorest emitter would not have needed to import the emitter directly, and any such specs would fail once this change is rolled out.

Only a single spec, which was just checked in this week shows this issue and will have this workaround applied as part of it.

**Back-compat design to avoid immediate breaking**
Specs would import `@azure-tools/typespec-autorest`  to avoid the issue.  We actually *want* them to break, however, because we want to remove spec dependencies on these decorators.  

**Impact**
This change affecting:

- [x] ARM
- [ ] Data-plane
- [x] Existing specs: 1
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: June 2024

**Additional information**
Add any other information about the change including fixes for here.
