### ISSUE TITLE
The type of `properties` in `SdkModelType` should be `SdkBodyModelPropertyType[]` since we could never get an instance of other types inside the array

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/typespec-azure#796]
### Clear and concise description of the problem

`SdkModelPropertyType` is a union of "model property" and "operation parameter", but because the property in a model type (in SDK's perspective) could never be a parameter, therefore the type of `properties` in `SdkModelType` should be narrow down to `SdkBodyModelPropertyType` only
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L287

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tadelesh** [comment]
@iscai-msft currently, it seems the only place we could not use `SdkBodyModelPropertyType` is the response type of service method which will mix http header parameter and model property. imo, for service method, the http parameter should also be a model property. for service operation, it definitely should be http parameter since it has protocol concept. but i'm a little bit confused with current logic.

**Comment by iscai-msft** [comment]
for options bags they can be non-body models, that's why we don't limit the properties of models
