### ISSUE TITLE
[tcgc] add lint rule for client customization

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#942]
need to force all client customization tsp content should be in `client.tsp` file.

**Comment by pshao25** [comment]
@tadelesh how you are going to define client customization? All the decorators from `typespec-client-generator-core`?

**Comment by tadelesh** [comment]
yes.

**Comment by lmazuel** [comment]
If we can, having a linter indeed to forbid "typespec-client-generator-core" import from any other files than "client.tsp". It may be complex though, depending on how the compiler is saving or not the origin of a given statement, it's possible the compiler first step is to merge everything into one thing (autorest was doing that)

**Comment by pshao25** [comment]
Synced offline with @timotheeguerin , the rule for raise linter is:
1) if the decorator is in client.tsp, then OK.
2) otherwise, raise warning.

Considering our future design: client.tsp will be imported by main.tsp, therefore everything will eventually be imported by main.tsp, we cannot make the rule as "whether the file where the decorator lies in is imported by main.tsp". 

If customers have such tsp
```
// client.tsp
import foo.tsp;

// foo.tsp
@clientName("another name")
model X {}
```
we will raise warning and they have to suppress themselves.

**Comment by pshao25** [comment]
Considering main.tsp is ultimate entrance, we don't need this feature.
