### ISSUE TITLE
[Bug]: TCGC generates incorrect cross-language definition IDs when client customization exists

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#961]
refer to this original issue: https://github.com/Azure/typespec-azure/issues/849

**Comment by iscai-msft** [comment]
this is what @tadelesh was talking about, where if there's client customizations in the `client.tsp` file, we need to make sure that it still corresponds with the old tsp file and what apiview generates. Is this something that apiview takes into consideration?

**Comment by tjprescott** [comment]
When generating APIViews, they should be pointing to main.tsp, not client.tsp. That used to be the case--though it may have changed (which would have been over my objection).

**Comment by iscai-msft** [comment]
We're continuing with our current code where we just look at the full namespace name from the service tsp, we had decided that for things specific to the `client.tsp` we can ignore since we can't link it up to the original typespec. That being said, I think I'll still try to just get a full namespace name for them so at least the client emitters can be unified. @bterlson is looking into a way that is more akin to hashing and won't run into the brittleness of matching by name, are there any updates there?

**Comment by tadelesh** [comment]
ok, then i believe we could close this issue for now.
